SERVER_IP="54.160.65.79"
SSH_KEY="/Users/xiaohai/.ssh/nexa.pem"
SSH_USER="ubuntu"
REMOTE_DIR="/home/ubuntu/apps/nexa-backend"
PRESERVE_ENV="true"

SSH_PORT="22"
STRICT_SYNC="true"
PRESERVE_NODE_MODULES="true"
RUN_NPM_CI_IF_LOCK_CHANGED="false"
RELOAD_PM2="false"
PM2_APP_NAME="nexa-backend"
