SERVER_IP="54.160.65.79"
SSH_KEY="/Users/xiaohai/.ssh/nexa.pem"
SSH_USER="ubuntu"
SSH_PORT="22"

REMOTE_WEB_DIR="/home/ubuntu/apps/nexa-legal-web"
STRICT_SYNC="true"
DRY_RUN="false"
FIX_PERMS="true"
FIX_HOME_TRAVERSE="true"
